### ISSUE TITLE
[Question] Implement latest changes

### ISSUE THREAD

**Issue by Thesergiolg99** [Apparence-io/CamerAwesome#410]
## Proposal

Ives seen you guys merged a pull request that added the onCapture option to the package, which is what i need. But the latest package in pub.dev is from 6 months back ,so it doent include this new option. How can i access into it?

Thanks!

**Comment by g-apparence** [comment]
Hi, 
Yes I'm working on the complete 2.0.0 release. 
The thing is I want to test all the example on more devices to be sure everything is ok. 
Also I have some improvements to add on the Lens selection on Android. 

Anyway you can use the master version using this in your pubspec 

```yaml
  camerawesome:
    git:
      url: https://github.com/Apparence-io/CamerAwesome
```

Once the version on pub is released I encourage you to switch on this version.

Hope It helps
